# Generated by Django 3.2.7 on 2021-10-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20211007_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applies',
            old_name='recejted_at',
            new_name='rejected_at',
        ),
    ]
